import {computed, ref} from "vue";
import {EMPTY_SCRIPT, ROLES} from "@/constants/roles";
import {SET_INDEX, ZERO_VERSION} from "@/constants/other";
import {isEmpty, isEqual} from "lodash/lang";

export const listWithParams = ref({})
export const characterListWithParams = ref({})
export const pdfListWithParams = ref(
    ROLES.reduce((acc, role) => {
        acc[role] = []
        return acc
    }, {})
)
export const pdfListElement = ref(null)
export const scriptList = ref([])
export const pdfMeta = ref(EMPTY_SCRIPT)
export const isOpenPdfOptions = ref(false)
export const isOpenNightOrder = ref(false)
export const activeScriptIndex = ref(SET_INDEX.DEFAULT)
export const activeVersion = ref(ZERO_VERSION)

export const isSavedScript = ref(false)

export const isWaitingOperation = ref(false)

export const isDeletingFromPdfCharacterList = ref(false)
export const activeScript = computed(() => scriptList.value[activeScriptIndex.value])

export const tags = ref([])

export const isEditScriptTags = ref(false)
export const isImportScript = ref(false)

export const isEditingScript = ref(false)
export const nightOrderAutoGenerated = ref(false)

export const filteredScriptListTags = ref([])
export const filteredScriptListCharacters = ref([])

const defaultNightArray = ['dusk', 'minioninfo', 'demoninfo', 'dawn']

const getDefaultFirstNight = () => {
  const rolesList = Object.values(pdfListWithParams.value).flat()
  const allRoles = [
    ...rolesList,
    { id: 'dusk', firstNight: 0, otherNight: 0 },
    { id: 'minioninfo', firstNight: 13 },
    { id: 'demoninfo', firstNight: 18 },
    { id: 'dawn', firstNight: 10000, otherNight: 10000 }
  ]
  return allRoles
      .filter(item => item.firstNight !== undefined)
      .sort((a, b) => a.firstNight - b.firstNight)
      .map(item => item.id)
}

const getDefaultOtherNight = () => {
  const rolesList = Object.values(pdfListWithParams.value).flat()
  const allRoles = [
    ...rolesList,
    { id: 'dusk', firstNight: 0, otherNight: 0 },
    { id: 'dawn', firstNight: 10000, otherNight: 10000 }
  ]
  return allRoles
      .filter(item => item.otherNight !== undefined)
      .sort((a, b) => a.otherNight - b.otherNight)
      .map(item => item.id)
}

export const isNightOrderMismatch = computed(() => {
  if (isEmpty(Object.values(pdfListWithParams.value).flat())) return false

  const currentFirstNight = pdfMeta.value.firstNight || []
  const currentOtherNight = pdfMeta.value.otherNight || []
  const defaultFirstNight = getDefaultFirstNight()
  const defaultOtherNight = getDefaultOtherNight()

  return !isEqual(currentFirstNight, defaultFirstNight) || !isEqual(currentOtherNight, defaultOtherNight)
})

