import {computed, ref, watch} from "vue";
import {EMPTY_SCRIPT, ROLES} from "@/constants/roles";
import {SET_INDEX, ZERO_VERSION} from "@/constants/other";
import {isEmpty, isEqual} from "lodash/lang";

export const listWithParams = ref({})
export const characterListWithParams = ref({})
export const pdfListWithParams = ref(
    ROLES.reduce((acc, role) => {
        acc[role] = []
        return acc
    }, {})
)
export const pdfListElement = ref(null)
export const scriptList = ref([])
export const pdfMeta = ref(EMPTY_SCRIPT)
export const isOpenPdfOptions = ref(false)
export const isOpenNightOrder = ref(false)
export const isOpenBootlegger = ref(false)
export const activeScriptIndex = ref(SET_INDEX.DEFAULT)
export const activeVersion = ref(ZERO_VERSION)

export const isSavedScript = ref(false)

export const isWaitingOperation = ref(false)

export const isDeletingFromPdfCharacterList = ref(false)
export const activeScript = computed(() => scriptList.value[activeScriptIndex.value])

export const tags = ref([])

export const isEditScriptTags = ref(false)
export const isImportScript = ref(false)

export const isEditingScript = ref(false)
export const nightOrderAutoGenerated = ref(false)
export const pdfGenerationError = ref(null)

export const filteredScriptListTags = ref([])
export const filteredScriptListCharacters = ref([])

// Trigger for focusing search input (incremented to trigger watch)
export const focusSearchTrigger = ref(0)

// Flag to prevent characterListWithParams overwrite after draft restore
export const isDraftRestored = ref(false)

// Flag to skip draft handling in onBeforeRouteLeave (when already handled in handleToScriptList)
export const skipDraftOnLeave = ref(false)

// Global flag for draft existence (updated by save/delete operations)
export const hasSavedDraft = ref(false)

const defaultNightArray = ['dusk', 'minioninfo', 'demoninfo', 'dawn']

const getDefaultFirstNight = () => {
  const rolesList = Object.values(pdfListWithParams.value).flat()
  const allRoles = [
    ...rolesList,
    { id: 'dusk', firstNight: 0, otherNight: 0 },
    { id: 'minioninfo', firstNight: 13 },
    { id: 'demoninfo', firstNight: 18 },
    { id: 'dawn', firstNight: 10000, otherNight: 10000 }
  ]
  return allRoles
      .filter(item => item.firstNight !== undefined)
      .sort((a, b) => a.firstNight - b.firstNight)
      .map(item => item.id)
}

const getDefaultOtherNight = () => {
  const rolesList = Object.values(pdfListWithParams.value).flat()
  const allRoles = [
    ...rolesList,
    { id: 'dusk', firstNight: 0, otherNight: 0 },
    { id: 'dawn', firstNight: 10000, otherNight: 10000 }
  ]
  return allRoles
      .filter(item => item.otherNight !== undefined)
      .sort((a, b) => a.otherNight - b.otherNight)
      .map(item => item.id)
}

// Сохранённый порядок ночи (заполняется при загрузке/сохранении скрипта)
export const savedFirstNightOrder = ref([])
export const savedOtherNightOrder = ref([])

// Базовый набор для Last Save (если нет сохранения)
const baseFirstNightOrder = ['dusk', 'minioninfo', 'demoninfo', 'dawn']
const baseOtherNightOrder = ['dusk', 'dawn']

// Получить last save (сохранённый порядок или базовый набор)
export const getLastSaveFirstNight = () => {
  return !isEmpty(savedFirstNightOrder.value) ? savedFirstNightOrder.value : baseFirstNightOrder
}

export const getLastSaveOtherNight = () => {
  return !isEmpty(savedOtherNightOrder.value) ? savedOtherNightOrder.value : baseOtherNightOrder
}

export const isNightOrderMismatch = computed(() => {
  if (isEmpty(Object.values(pdfListWithParams.value).flat())) return false

  const currentFirstNight = pdfMeta.value.firstNight || []
  const currentOtherNight = pdfMeta.value.otherNight || []
  const lastSaveFirstNight = getLastSaveFirstNight()
  const lastSaveOtherNight = getLastSaveOtherNight()

  // Предупреждение если current отличается от last save
  return !isEqual(currentFirstNight, lastSaveFirstNight) || !isEqual(currentOtherNight, lastSaveOtherNight)
})

